### ISSUE TITLE
ポーズメニューを作る

### ISSUE THREAD

**Issue by Shi-553** [Shi-553/RampageCars#102]
## 何が問題なのか
* ゲームを一時停止したい。
* やり直したい。
* タイトルに戻りたい。

## 望む解決策
* ゲームの上に被せる新しいポーズメニューシーンを作る。
* ゲーム止めるー＞ポーズメニューシーンを追加でロードー＞タイトルに遷移か、リトライか、ポーズメニューシーンアンロード

## 補足説明
タイトルシーン、ゲームオーバーシーンを参考にする。
https://www.youtube.com/watch?v=Hn804Wgr3KE

**Comment by chage401** [comment]
上記に加えて「操作説明」の枠が欲しい

**Comment by a-six666** [comment]
テキストベースで操作方法を書く
例・R1/L1　=　ドリフト　みたいな感じ

操作系が完全に固まったらデザイナーさんに操作説明画像をお願いして、そちらに差し替えるかも
