### ISSUE TITLE
地形を作る

### ISSUE THREAD

**Issue by Shi-553** [Shi-553/RampageCars#11]
## 何が問題なのか
挙動を確認したり、イメージを膨らませることができない。

## 望む解決策
sampleシーンにジャンプ台を設置する。

## 補足説明
ただの板?

**Comment by a-six666** [comment]
三角柱のような地形を最初に追加してみてもらいたいです
![cc04](https://user-images.githubusercontent.com/73224443/156995018-5b470497-7806-4b5f-a7fe-f6aaeab47757.jpg)
