### ISSUE TITLE
ワイパー中のヒゲの無敵化

### ISSUE THREAD

**Issue by Shi-553** [Shi-553/RampageCars#110]
## 何が問題なのか
プレイヤーのアクション「ワイパー」を使ってもヒゲ経由でダメージを受けるので弱い。

## 望む解決策
ワイパー中はヒゲからダメージを受けないようにする。

## 補足説明
ワイパー中もボディなどはこれまでどおりダメージを受ける。

**Comment by Ren-Takeuchi** [comment]
ワイパー使用後に思いっきりダメージを受ける気がするのでそこも見てみてほしいです
