### ISSUE TITLE
もっと厳密にリスポーンさせる

### ISSUE THREAD

**Issue by Shi-553** [Shi-553/RampageCars#135]
## 何が問題なのか
* 落ちた場所から一番近いところにリスポーンするのでショートカットなどが可能。
* 落ちた場所からリスポーン地点への方向を向いてリスポーンするので変な方向を向いていることがある。

## 望む解決策
* プレイヤーが地面についているときのみリスポーン地点を更新するようにする。
* リスポーン時の向きを決められるようにする。

**Comment by a-six666** [comment]
プレイヤーから見えないリスポーン地点をステージに複数設け、落下した場合はエリア毎の特定のリスポーン地点からやり直す方法でお願いします。
大きいコライダーを作りコライダー内に入ったらプレイヤーのリスポーンポイントが更新されるような作りにしてください。
