### ISSUE TITLE
エンドボタンの追加

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#31]
## 何が問題なのか
ゲームを終了する方法がない

## 望む解決策
ゲームが終了するボタンを実装する
コントローラならBackボタン
キーボードはLに設定

## 検討した代替案
特になし

## 補足説明
特になし

**Comment by toiwd** [comment]
@Shi-553 これってゲーム終了のコードをUnRealCarに入れた方がいい？それともEventSystemのオブジェクトに新しくスクリプト作ってそこにコード書き込んだ方がいい？
