### ISSUE TITLE
ゲーム内にタイム追加

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#60]
## 何が問題なのか
ゲーム内にタイムを実装したい

## 補足説明
ゲーム内でタイムを表示して「0」になったらゲームを止めて、ゲームオーバー画面に遷移。
タイムの初期値は「180」秒

**Comment by Shi-553** [comment]
#61 でシーン遷移させるため、
単体では遷移せず「0」になったときのイベントを作ってください。
