### ISSUE TITLE
ゲームオーバー画面の追加

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#61]
## 何が問題なのか
ゲームオーバーのシーンを作ってほしい

## 補足説明
「タイムが０になる」もしくは「プレイヤーの体力が０になる」
いずれかの条件を満たしたときに、ゲームオーバーになるようにしてほしい。
またゲームオーバーになったら「リトライ」か「ゲーム終了」を選択できるようにしてほしい

**Comment by Shi-553** [comment]
先にゲームオーバーシーンを作って一回プルリクエスト。
その後#60 と#62 ができたら`GameTransition.cs`を作って、シーン遷移関数をタイマーとプレイヤーのイベントに登録してください。
