### ISSUE TITLE
プレイヤーアクション「ダイブ」追加

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#66]
## 何が問題なのか
プレイヤーが「A」を入力したら衝撃波を発生させ、敵に当たったらダメージを与える
衝撃波は当たり判定がどこまで出ているか分かるように作ってほしい
与えるダメージは暫定で「10」

## 補足説明
プランナー側で数値と範囲を調整できると助かります

**Comment by Shi-553** [comment]
`PlayerController`の`JumpStarted`で`DoAction`を呼んでください。

**Comment by Shi-553** [comment]
`AccelPlayerAction`をまねして`MonoBehaviour,IPlayerAction`を継承した`DivePlayerAction`を作ってください。
空中判定は`GroundChecker`をインスペクターでアタッチしてください。

また、呼ぶときは`PlayerController`の`JumpStarted`で`DoAction<DivePlayerAction>()`を呼んでください。

**Comment by a-six666** [comment]
@Shi-553 確かにアタックだと分かりにくいので「ダイブ」でお願いします

**Comment by toiwd** [comment]
@Shi-553 Physics.OverlapSphereを利用して、範囲内の敵のColliderを取得してダメージを与えようと思ってます。ダメージ判定をOnCollisionEnter内にあるdamageble.Publish()を参考して作成しようとしているのですが、Collision型を引数として指定されているのでCollider型はやっぱり使えないのでしょうか。連絡遅くなって申し訳ないですが、対処法を教えていただきたいです。

**Comment by toiwd** [comment]
if(!groundChecker.IsGrounded)
                {
                    Collider[] targets = Physics.OverlapSphere(transform.position, range);
                    
                    foreach (Collider colliders in targets)
                    {
                        var damageable = colliders.gameObject.GetComponent<IPublishable<CollisionDamageInfo>>();
                        if (damageable is not null and IEnemyTag)
                        {
                            damageable.Publish(new (attack, colliders));
                        }
                    }
                    
                }
                CanChange = true;
こんな感じで作ろうとしてます。

**Comment by toiwd** [comment]
if (!groundChecker.IsGrounded)
                {
                    Collider[] targets = Physics.OverlapSphere(transform.position, range);
                    foreach (Collider colliders in targets)
                    {
                        var damageable = colliders.gameObject.GetComponent<IPublishable<CollisionDamageInfo>>();
                        if (damageable is not null and IEnemyTag)
                        {
                            damageable.Publish(new (attack, colliders));
                        }
                    }
                }

こんな感じで作ろうとしてます。

**Comment by toiwd** [comment]
`if (!groundChecker.IsGrounded)
                {
                    Collider[] targets = Physics.OverlapSphere(transform.position, range);
                    foreach (Collider colliders in targets)
                    {
                        var damageable = colliders.gameObject.GetComponent<IPublishable<CollisionDamageInfo>>();
                        if (damageable is not null and IEnemyTag)
                        {
                            damageable.Publish(new (attack, colliders));
                        }
                    }
                }`
こんな感じで作ろうと思ってます。

**Comment by toiwd** [comment]
`
if (!groundChecker.IsGrounded)
                {
                    Collider[] targets = Physics.OverlapSphere(transform.position, range);
                    foreach (Collider colliders in targets)
                    {
                        var damageable = colliders.gameObject.GetComponent<IPublishable<CollisionDamageInfo>>();
                        if (damageable is not null and IEnemyTag)
                        {
                            damageable.Publish(new (attack, colliders));
                        }
                    }
                }
`
こんな感じで作ろうと思ってます。

**Comment by Shi-553** [comment]
Collision型必要なのは設計ミスなのでとりあえずnull入れれば大丈夫です。
TestEnemyで使ってないはずだし、あとで使わないようにします。

**Comment by toiwd** [comment]
わかりました。ありがとうございます。

**Comment by toiwd** [comment]
@Shi-553 何度もすみません。damageable.Publish(new (attack, null));と記述すると、NullReferenceExceptionのエラーが出るのですが、どこか間違ってたりしますか？対処法を教えていただきたいです。

**Comment by Shi-553** [comment]
https://github.com/Shi-553/RampageCars/blob/c2a0fe32ed12d345eb9cd1cc0a84500570a33624/Assets/C%23/PubSub/ICollisionDamageInfo.cs#L12
吹っ飛ばす方向決めるのにcollision使ってたので、こっちのオーバーロード使ってください。

**Comment by toiwd** [comment]
解決しました。何度もありがとうございます。
