### ISSUE TITLE
雑魚敵が攻撃してくるように

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#70]
## 何が問題なのか
カプセルが一定以上近づいたプレイヤーに対して近接攻撃を行うようにしてほしい
また攻撃する直前にどの範囲を攻撃するか表示するようにしてほしい
ダメージは暫定で「1」に設定

## 補足説明
攻撃までのタイミングや、攻撃範囲、攻撃を開始する距離をプランナー側で調整できると助かります

**Comment by Shi-553** [comment]
@a-six666 
敵は移動しなくて大丈夫ですか？

**Comment by a-six666** [comment]
@Shi-553 移動しないで大丈夫です

**Comment by Shi-553** [comment]
今時間あるので担当変更しました
