### ISSUE TITLE
「海」の追加

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#79]
## 何が問題なのか
「海」の地形を追加してほしい
## 補足説明
海の機能は以下の通り
・敵が触れると即死する
・プレイヤーが触れると体力が「5」減少し、近くの海でない地形にワープする(マリオカートのコースアウトした時みたいな処理)

見た目は鯖ちゃんの作ってくれたものを使ってください

**Comment by toiwd** [comment]
@Shi-553 プレイヤーへのダメージってどういった感じで加えればいいですか？

**Comment by Shi-553** [comment]
海を`isTrigger`がオンのコライダーで当たり判定取ってたら
こんなスクリプトを付ければダメージはいるはずです

```C#
        private void OnTriggerEnter(Collider collision)
        {
            var publishable=collision.collider.GetComponent<IPublishable<DamageInfo>>();
            if (publishable is not null and IPlayerTag)
            {
                publishable.Publish(new(ここにダメージ量));
            }
        }
```

**Comment by toiwd** [comment]
@Shi-553 理解した！
ありがとうございます！

**Comment by toiwd** [comment]
@Shi-553 夜遅くにごめんなさい
OnTriggerEnterだとif (publishable is not null and IPlayerTag)の中身を通ってくれないのですがどうすればいいですか？

**Comment by Shi-553** [comment]
collisionにプレイヤーは入ってきてる？

**Comment by toiwd** [comment]
@Shi-553 海のcollisionにプレイヤーが入ってると思います

**Comment by Shi-553** [comment]
`PlayerCore`みればわかるんだけど、実装してるの`IPublishable<CollisionDamageInfo>`だったからをこっちを`GetComponent`して、
`impulse`はゼロとかにしてください

**Comment by toiwd** [comment]
@Shi-553 やってみます。ありがとうございます。
ちなみにif (publishable is not null and IEnemyTag)の中も通ってくれないのですが、そちらもこの変更で解決しますか？

**Comment by Shi-553** [comment]
`GetComponent`でとってきた変数が`null`じゃなくて、`IPlayerTag`を実装してるときって条件だからとおるはず

**Comment by Shi-553** [comment]
ごめん`IEnemyTag`のほうかそっちも`TestEnemy`がとおるはず

**Comment by toiwd** [comment]
@Shi-553 既存のコードいろいろ参考にして
private void OnTriggerEnter(Collider collision)
        {
            var publishable = collision.gameObject.GetComponent<IPublishable<CollisionDamageInfo>>();
            if (publishable is not null and IPlayerTag)
            {
                var impulse = new Vector3(0, 0, 0);
                publishable.Publish(new (playerDamage,null, impulse));
            }
            if (publishable is not null and IEnemyTag)
            {
                var impulse = new Vector3(0, 0, 0);
                publishable.Publish(new (enemyDamage,null, impulse));
            }
        }
って感じにしたんですが、Enemyはダメージ入ってもPlayerにはダメージが入らないです。どうすればいいでしょうか

**Comment by Shi-553** [comment]
ifの中のブレークポイントで止まる？

**Comment by toiwd** [comment]
@Shi-553 ブレークポイントは試してないですが、ifの中にDebug.Log入れて確かめても出力されなかったです

**Comment by Shi-553** [comment]
忘れてた`PlayerCore`がプレイヤーについてなかった
HPBarについてると思うからコピー、削除してプレイヤーのBodyにペーストして

**Comment by toiwd** [comment]
@Shi-553 「Body」ゲームオブジェクトに「Rigidbody」がアタッチされていませんが、スクリプトがそれにアクセスしようとしています。ってエラーを吐かれたので、Player自体にスクリプトをつけたのですが動きません。どうすればいいでしょうか

**Comment by Shi-553** [comment]
`PlayerCore`内の`GetComponent`を`GetComponentInParent`にすれば動くはず

**Comment by toiwd** [comment]
@Shi-553 上手くいきました。こんな時間まで本当にありがとうございました。
