### ISSUE TITLE
仮のエフェクト、効果音の追加

### ISSUE THREAD

**Issue by Shi-553** [Shi-553/RampageCars#9]
## 何が問題なのか
「感触」を確認するため最低限の装飾が欲しい。

## 望む解決策
* 爆発エフェクト
* 爆発した時の効果音
* 敵に当たった時のエフェクト
* 敵に当たった時の効果音

の追加。

## 補足説明
フリー素材を使う

**Comment by a-six666** [comment]
デザイナーさんが作ってくれたものの実装も試したいので素材は鯖ちゃんが上げてくれたものを使ってください
https://discordapp.com/channels/760825555553222696/772346639649996811/949966046494867466
