### ISSUE TITLE
氷床マップチップの追加

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#90]
マップを作る際に使う氷床を追加して欲しいです
・icefloor_plane
・icefloor_side
・icefloor_corner2_L
・icefloor_corner2_R
・icefloor_corner1
・icefloor_corner3_R
・icefloor_corner3_L
・icefloor_corner4_L
・icefloor_corner4_R
・icefloor_corner_mini
それぞれ個別で追加してもらい、マップ制作時にプランナー側で組み立てるつもりです。

当たり判定はできるだけ見た目に沿うようにして頂けると助かります。

**Comment by Shi-553** [comment]
氷床素材の場所です
https://discord.com/channels/760825555553222696/952072455474786335/972519022807633930
