### ISSUE TITLE
ゲームタイトル画面の追加

### ISSUE THREAD

**Issue by a-six666** [Shi-553/RampageCars#97]
ゲームタイトル画面を追加し、タイトルロゴを入れてみて欲しいです。
タイトルロゴの他には
・ゲームスタート(押すとステージ1に遷移。現状はステージ1がないためサンプルシーンに遷移。)
・ゲーム終了
の2つのボタンを用意して、コントローラで選択できるように実装してもらいたいです。

ボタンやタイトルロゴの配置はUI担当の方と相談して位置を再調整するつもりです。

**Comment by Shi-553** [comment]
@a-six666 
タイトルロゴってどこかにありますか？
テキストで代用でしょうか？

**Comment by a-six666** [comment]
ゲームタイトルはこのリンク先に上がっている素材を使って下さい
https://discordapp.com/channels/760825555553222696/952073126064312350/971951728373141534
